version: "3.9"

services:
  
  server:
    container_name: server
    build: .
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
  
  db:
    container_name: db
    image: "postgres"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
  