version: "3.9"

services:
  
  compsigh_api:
    container_name: compsigh_api
    build: .
    depends_on:
      - compsigh_postgres_db
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - src_data:/usr/src/app
  
  compsigh_postgres_db:
    container_name: compsigh_postgres_db
    image: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  src_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/src
  postgres_data: